# Generated by Django 4.2.3 on 2023-07-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_orderout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivers',
            name='status',
            field=models.CharField(choices=[('Подготовка к отправке', 'Подготовка к отправке'), ('В пути', 'В пути'), ('Прибыл в пункт назначения', 'Прибыл в пункт назначения')], max_length=50, unique=True),
        ),
    ]
