# Generated by Django 4.2.3 on 2023-07-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_alter_orderout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Подготовка к отправке', 'Подготовка к отправке'), ('В пути', 'В пути'), ('Прибыл в пункт назначения', 'Прибыл в пункт назначения')], max_length=50),
        ),
    ]
